### PR TITLE
Refactor: Use counter for group macros

### PR DESCRIPTION
**Pull request by BrettMayson**
Personally I prefer this as you don't need to declare a macro for each, don't need to worry about calling them in the correct order, although you do need to call `__COUNTER_RESET__` at the start

Depends on #107 because I was using a dev build of HEMTT that doesn't like the current master. Looks like current HEMTT also doesn't like `__COUNTER_RESET__` for some reason.

(This PR will look better once #107 is on master)

### CODE REVIEW

**Comment by BrettMayson** [comment]
@Mike-MF Are you interested in this? Do I update it?

**Comment by Mike-MF** [comment]
eh, It's a lot of work I'd just close it

**Comment by BrettMayson** [comment]
I mean, not really. just a preference thing

**Comment by jonpas** [comment]
I like it, it simplifies things.

**Comment by Mike-MF** [comment]
Feel free, might be placebo but using ranks more "correctly" seems to actually affect how quickly group leaders change with less downtime on AI actually doing stuff. Added it into the macro below how it is currently, hopefully it's right as I'm still mostly asleep.

```
// Group Macros
#define GROUP_UNIT(UNIT,SIDE) __GROUP_UNIT(__COUNTER__, UNIT, SIDE)

#define __GROUP_UNIT(COUNTER, UNIT, SIDE) \
    class unit##COUNTER { \
        vehicle = #UNIT; \
        side = SIDE; \
        #if COUNTER == 0 \
        rank = "SERGEANT"; \
        #else \
        #if COUNTER == 2 \
        rank = "SERGEANT"; \
        #else \
        #if COUNTER == 3 \
        rank = "CORPORAL"; \
        #else \
        #if COUNTER == 5 \
        rank = "SERGEANT"; \
        #else \
        #if COUNTER == 6 \
        rank = "CORPORAL"; \
        #else \
        rank = "PRIVATE"; \
        #endif \
        #endif \
        position[] = { \
            QUOTE(5 * floor ((COUNTER + 1) / 2) * (-1 ^ (COUNTER + 1))), \
            QUOTE(-5 * floor ((COUNTER + 1) / 2)), \
            0 \
        }; \
    }
```

**Pull request closed without merging**
